# for data preparation
WINSORIZATION_FACTOR = 3

# data loading during training
COUNT_PERCENTILE_THRESHOLD = 0.01
CV_PERCENTILE_THRESHOLD = 0.99
CHUNKS_PER_BATCH = 1

# multi-task training
DESCRIPTOR_LOSS_WEIGHT = 1.0
FINGERPRINT_LOSS_WEIGHT = 1.0
