# for data preparation
WINSORIZATION_FACTOR = 6

# for training
DROPOUT_FRACTION = 0.30
EPOCHS = 20
PATIENCE = 2
INITIAL_LEARNING_RATE = 0.00001
MAXIMUM_LEARNING_RATE = 0.0001
FINAL_LEARNING_RATE = 0.0001
WARMUP_EPOCHS = 2
CHUNKS_PER_BATCH = 2

# model hyperparameters
FNN_HIDDEN_SIZE = 2_048
FNN_HIDDEN_LAYERS = 1
FNN_ACTIVATION = "relu"
MP_HIDDEN_SIZE = 2_048
MP_DEPTH = 6
MP_ACTIVATION = "relu"
FEATURIZER = "rigr"  # one of: "default", "rigr"
