# for data preparation
WINSORIZATION_FACTOR = 3

# for training
DROPOUT_FRACTION = 0.70  # see: https://doi.org/10.1039/D5DD00369E -> 60% mask = 40% dropout
EPOCHS = 5
PATIENCE = 1
INITIAL_LEARNING_RATE = 0.00001
MAXIMUM_LEARNING_RATE = 0.0001
FINAL_LEARNING_RATE = 0.00001
WARMUP_EPOCHS = 1
CHUNKS_PER_BATCH = 2

# model hyperparameters
FNN_HIDDEN_SIZE = 2_048
FNN_HIDDEN_LAYERS = 1
FNN_ACTIVATION = "LEAKYRELU"  # one of: RELU, LEAKYRELU, PRELU, TANH, ELU
MP_HIDDEN_SIZE = 2_048
MP_DEPTH = 6
MP_ACTIVATION = "LEAKYRELU"  # one of: RELU, LEAKYRELU, PRELU, TANH, ELU
FEATURIZER = "RIGR"  # one of: "V2", "RIGR"
